#!/bin/sh

make -C lib/colord check || (cat lib/colord/test-suite.log && false)
make -C lib/colorhug check || (cat lib/colorhug/test-suite.log && false)
make -C src check || (cat src/test-suite.log && false)
